USE DB_VENDAS
-- AULA DE FUNÇÕES

-- MANIPULANDO TEXTOS, DATATYPES DE CARACTER

-- SUBISTRING EXTRAIR UMA PALAVRA   ( NOMA DA COLUNA, VALOR ONDE COMEÇA, E TAMANHO DO NOME EM CARACTERES)

SELECT 'GUSTAVO MENDAS FERREIRA',
SUBSTRING('GUSTAVO MENDES FERREIRA', 9,6)

SELECT NOME, SUBSTRING(NOME,7,8)
FROM TB_EMPREGADO
WHERE NOME = 'OLAVO TRINDADE'

-- LEFT (COLUNA, VALOR DE CARAC QUE VAI PEGAR)

SELECT 'GUSTAVO MENDAES FRREIRA',
		LEFT('GUSTAVO MENDAES FRREIRA',7)

SELECT NOME, LEFT(NOME,5)
FROM TB_EMPREGADO
WHERE NOME = 'OLAVO TRINDADE'

-- RIGHT PEGA DO FINAL DA PALAVRA (COLUNA, VALOR DE CARACT)
SELECT 'GUSTAVO MENDAES FRREIRA',
		RIGHT('GUSTAVO MENDAES FERREIRA',8)

SELECT NOME, RIGHT(NOME,8)
FROM TB_EMPREGADO
WHERE NOME = 'OLAVO TRINDADE'

-- TODO MUNDO QUE O ULTIMO NOME É SILVA  abrir o showplan ctrl + L

SELECT * FROM TB_EMPREGADO
WHERE RIGHT(NOME,5) = 'SILVA'

SELECT * FROM TB_EMPREGADO
WHERE NOME LIKE '%SILVA'

-- UPPER  DEIXA TUDO MAIÚSCULO 
SELECT 'Gustavo	Mendes ferreira',
		UPPER('Gustavo	Mendes ferreira')

SELECT
	E_MAIL			OBSERVAÇÃO,
	UPPER(E_MAIL)	OBSERVAÇÃO
FROM TB_CLIENTE

-- LOWER DEIXA TUDO MINÚSCULO 

SELECT 'GUSTAVO MENDES FERREIRA',
	LOWER('GUSTAVO MENDES FERREIRA')

SELECT NOME,
	LOWER(NOME)
FROM TB_CLIENTE

--LTRIM TIRA ESPAÇO EM BRANCO DO COMEÇO       ORDER BY 2 POR EXEMPLO PEGA A SEGUNDA COLUNA QUE FOI PRO SELECT COMO PARÂMETRO
SELECT '      GUSTAVO MENDES',
	LTRIM('      GUSTAVO MENDES')

SELECT DISTINCT
	CIDADE,
	LTRIM(CIDADE)
FROM TB_CLIENTE
ORDER BY 2 

-- RTRIM TIRA ESPAÇOS EM BRANCO DO FINAL
SELECT '      GUSTAVO MENDES     ',
		RTRIM('      GUSTAVO MENDES     ')

-- RTRIM N LTRIM TOGETHER
SELECT '      GUSTAVO MENDES     ',
	RTRIM(LTRIM('      GUSTAVO MENDES     '))

--LEN DESCOBRE A QNT DE CARAC QUE TEM NA STRING

SELECT
	NOME,
	LEN(NOME)
FROM TB_CLIENTE

--CHARINDEX PEGAR A POSIÇÃO DA LETRA OW ESPAÇO EM BRANCO

SELECT
	NOME,
	CHARINDEX(' ',NOME)
FROM TB_EMPREGADO

-- EXTRAINDO O PRIMEIRO NOME

SELECT
	NOME,
	CHARINDEX(' ',NOME) POSICAO_ESPACO,
	LEFT(NOME,CHARINDEX(' ',NOME))			PRIMEIRO_NOME,
	RTRIM(LEFT(NOME,CHARINDEX(' ', NOME)))	PRIMEIRO_NOME
FROM TB_EMPREGADO

-- EXTRAINDO O SOBRENOME

SELECT
	NOME,
	LEN(NOME)							QTD_CARACTERES,
	CHARINDEX(' ',NOME)					POSICAO_ESPACO,
	LEN(NOME) - CHARINDEX(' ',NOME)		QTD_CARACTERES_APOS_ESPACO,
	RIGHT(NOME, LEN(NOME) - CHARINDEX(' ',NOME)) SOBRENOME
FROM TB_EMPREGADO

-- EXIBIR O PRIMEIRO NOME EO SOBRE NOME EM COLUNAS APARTADAS

SELECT
	RTRIM(
		LEFT(
			NOME,
			CHARINDEX(' ',NOME)
			)
		   ) PRIMEIRO_NOME,
		RIGHT(
		NOME,
		LEN(NOME)-CHARINDEX(' ',NOME)
		) SOBRENOME
FROM TB_EMPREGADO


-- REPLACE TROCAR UM CARACT POR OUTRO

SELECT
	'AEIOU',
	REPLACE('AEIOU', 'I', ' '),  -- AQUI ESTÁ PEGANDO UM VALOR DE DENTRO DA STRING E TROCANDO PELO ULTMO VALOR 
	REPLACE('AEIOU', 'I', '')

SELECT
	NOME,
	ENDERECO,
	REPLACE(
			REPLACE(
				REPLACE(ENDERECO, 'R.', 'RUA '),
				'TRAV.', 'TRAVESSA '),
			'AV.', 'AVENIDA ') ENDERECO_TRATADO
FROM TB_CLIENTE

--CASE

-- RETONRAR A LOCALIZAÇÃO GEOGRAFICA DO CLIENTE

SELECT
	NOME,
	ESTADO,
	CASE
		WHEN ESTADO IN ('DF','GO','MS','MT') THEN 'CENTRO-OESTE'
		WHEN ESTADO IN ('BA','CE','MA','PB','PE','RN') THEN 'NORDESTE'
		WHEN ESTADO IN ('AM','PA','PI','TO','RR','RO','AC') THEN 'NORTE'
		WHEN ESTADO IN ('ES','MG','SP','RJ') THEN 'SUDESTE'
		WHEN ESTADO IN ('PR','SC','RS') THEN 'SUL'
		ELSE 'NÃO INFORMADO'
	END AS REGIAO
FROM TB_CLIENTE

SELECT
	NOME,
	ENDERECO,
	IIF(    ENDERECO LIKE 'AV.%', 
		    REPLACE(ENDERECO, 'AV.','AVENIDA '),
		    REPLACE(REPLACE(ENDERECO,'R.','RUA ',), 'TRAV.', 'TRAVESSA ')
		)
FROM TB_CLIENTE

--FUNÇÕES DE DATA 
SELECT 
	NOME,
	DATA_NASCIMENTO,
	YEAR(DATA_NASCIMENTO) ANO_NASCIMENTO,
	MONTH(DATA_NASCIMENTO) MES_NASCIMENTO,
	DAY(DATA_NASCIMENTO) DIA_NASCIMENTO
FROM TB_EMPREGADO

-- TODOS OS EMPREGADOS NASCIDOS NA DECADA DE 50
SELECT
	*
FROM TB_EMPREGADO
WHERE YEAR(DATA_NASCIMENTO) BETWEEN 1950 AND 1959

-- DATA E HORA DO SERVER
SELECT GETDATE()

-- DATEDIFF
SELECT
	NOME,
	DATA_NASCIMENTO,
	DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) DIFERENCA_ANOS,
	DATEDIFF(DAY, DATA_NASCIMENTO,GETDATE()) / 365
FROM TB_EMPREGADO 

--DATEADD(parte da data,valor,data)

SELECT DATEADD(DAY,25,GETDATE())		DATA_25POSTERIOR,
	   DATEADD(MONTH, -2, GETDATE())	DATA_2MESES_ANTERIOR

-- EXIBA A OSSÍVEL DATA DE ENTREHA, CONSIDERANDO 3 DIAS COMO PADRÃO
SELECT
	*,
	DATEADD(DAY,3,DATA_EMISSAO) DARA_ENTREGA_INFERIDA
FROM TB_PEDIDO

-- PEDIDOS EMITIDOS EM ATÉ 4 ANOS
SELECT
	*
FROM TB_PEDIDO
WHERE DATA_EMISSAO >= DATEADD(YEAR, -4,GETDATE())

-- DATEPART (PARTE DA DATA, EXPRESSÃO) QUARTER = TRIMESTRE  

SELECT
	*,
	DATEPART(WEEKDAY,DATA_EMISSAO) DIA_SEMANA_EMISSAO_PEDIDO,
	CASE DATEPART(WEEKDAY,DATA_EMISSAO)
	WHEN 1 THEN 'DOMINGO'
	WHEN 2 THEN 'SEGUNDA'
	WHEN 3 THEN 'TERÇA'
	WHEN 4 THEN 'QUARTA'
	WHEN 5 THEN 'QUINTA'
	WHEN 6 THEN 'SEXTA'
	WHEN 7 THEN 'SÁBADO'
FROM TB_PEDIDO

-- TODOS OS PEDIDOS EMITIDOS NOS PRIMEIROS TRIMESTRES (INDEPENDENTE DO ANO)
SELECT 
	*
FROM TB_PEDIDO
WHERE DATEPART(QUARTER, DATA_EMISSAO) - 1

-- VALOR ALEATÓRIO ENTRE 100 E 200
SELECT 
	100 + RAND() * 100

--ROUND ARREDONDAMENTO DE CASAS DECIMAIS TANTO PRA CIMA QUANTO PRA BAIXO 

SELECT 
	NUM_PEDIDO,
	VLR_TOTAL,
	ROUND(VLR_TOTAL,1) VLR_TOTAL_ARRED_1DECIMAL,
	ROUND(VLR_TOTAL,0) VLR_TOTAL_ARRED_1DECIMAL,
	CAST(VLR_TOTAL AS INT) VER_TOTAL_INTEIRO,
	CAST(ROUND(VLR_TOTAL,0) AS INT) VLR_TOTAL_INTEIRO_ARRED
FROM TB_PEDIDO

-- CAST FAZ O CONVERSÃO DO DATATYPE DO QUE FOR UTILIZADO
SELECT
	CAST(0 AS DATETIME),
	CAST(1.5 AS DATETIME),
	CAST(1000/24/60 AS DATETIME),
	CAST(GETDATE() AS INT)

SELECT SALARIO,
	'R$ ' + CAST(SALARIO AS VARCHAR(10))
FROM TB_EMPREGADO

-- CONVERT

SELECT
	NOME,
	DATA_NASCIMENTO,
	CONVERT(VARCHAR(10), DATA_NASCIMENTO, 103) DATA_NASCIMENTO_FORMATADA,
	CONVERT(VARCHAR(10), DATA_NASCIMENTO, 105) DATA_NASCIMENTE_FORMATADA
FROM TB_EMPREGADO 

-- FORMAT 
SELECT
	NOME,
	DATA_NASCIMENTO,
	FORMAT(DATA_NASCIMENTO, 'dd/MM/yyyy','pt-BR') as DATA_NASCIMENTO_FORMATADA,
	UPPER(FORMAT(DATA_NASCIMENTO, 'dd/MM/yyyy','pt-BR')) as DATA_NASCIMENTO_FORMATADA
FROM TB_EMPREGADO

