USE DB_VENDAS

-- OPERADORES MATEMÁTICOS + - * / %
/*
	+ ADIÇÃO          ENTRE STRING OW ALGO NÃO VALOR INTEIRO ELE CONCATENA 
	- SUBITRAÇÃO 
	* MULTIPLICAÇÃO   SE NÃO TIVER ENTRE DOIS VALORES, ELE VAI PERGAR O VALOR TOTAL COMO O
					  SELECT *
	/ DIVISÃO
	% RESTO DA DIVISÃO 
*/

SELECT  
	NOME,
	SALARIO,
	PREMIO_MENSAL,
	SALARIO *1.1					'SALÁRIO REAJUSTADO',
	SALARIO + PREMIO_MENSAL			AS SALARIO_PREMO,
	SALARIO + PREMIO_MENSAL * 12	AS SALARIO_ANUAL_ERRO ,
	(SALARIO + PREMIO_MENSAL) * 12  AS SALARIO_ANUALUALIZADO
FROM TB_EMPREGADO 

-- EXIBIR EM QUAIS CIDADES HÁ CLIENTES 
SELECT DISTINCT -- DISTINCT EVITA A REPETIÇ~ÇAO DE NOMES 
	CIDADE
FROM TB_CLIENTE

SELECT DISTINCT 
	CIDADE, NOME  -- PEGA O CONJUNTO DE COLUNAS DISTINTAS 
FROM TB_CLIENTE 

