-- FUNÇÕES DE AGREGAÇÃO
USE DB_VENDAS

SELECT 
	AVG(SALARIO)               MEDIA_SALARIO,
	SUM(SALARIO)			   SOMA_SALARIO,
	COUNT(SALARIO)             QTD_EMPREGADOS_COM_SALARIO,
	COUNT(*)                   QTD_EMPREGADOS, -- SÓ FUNC COUNT ACEITA '*'
	COUNT(DISTINCT COD_DEPTO)  QTD_DEPARTAMENTOS_DIFERENTES,
	COUNT(COD_DEPTO)           QTD_DE_EMPREGADOS_C_DEPARTAMENTOS,
	MIN(DATA_ADMISSAO)         DATA_ADMISSAO_MAIS_ANTIGA,
	MAX(DATA_NASCIMENTO)       DATA_NASCIMENTO_MAIS_RECENTE
FROM TB_EMPREGADO

--MÉDIA SALARIAL, TOTAL GASTO COM SALÁRIO, O MENOR E O MAIOR SALÁRIO, SOMENTE DO DEPARTAMENTO 1

SELECT
	AVG(SALARIO)		MEDIA_SALARIAL,
	SUM(SALARIO)		TOTAL_GASTO_SALARIO,
	MIN(SALARIO)		MENOR_SALARIO,
	MAX(SALARIO)		MAIOR_SALARIO
FROM TB_EMPREGADO
WHERE COD_DEPTO = 1

--MÉDIA SALARIAL, TOTAL GASTO COM SALÁRIO, O MENOR E O MAIOR SALÁRIO, POR DEPARTAMENTO

SELECT
	COD_DEPTO,
	AVG(SALARIO)		MEDIA_SALARIAL,
	SUM(SALARIO)		TOTAL_GASTO_SALARIO,
	MIN(SALARIO)		MENOR_SALARIO,
	MAX(SALARIO)		MAIOR_SALARIO,
	COUNT(*)			QTD_EMPREGADOS
FROM TB_EMPREGADO
GROUP BY COD_DEPTO

SELECT
    TB_EMPREGADO.COD_DEPTO,
	TB_DEPARTAMENTO.DEPTO,
	AVG(SALARIO)		MEDIA_SALARIAL,
	SUM(SALARIO)		TOTAL_GASTO_SALARIO,
	MIN(SALARIO)		MENOR_SALARIO,
	MAX(SALARIO)		MAIOR_SALARIO,
	COUNT(*)			QTD_EMPREGADOS

FROM TB_EMPREGADO
	JOIN TB_DEPARTAMENTO
	ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
GROUP BY TB_EMPREGADO.COD_DEPTO, TB_DEPARTAMENTO.DEPTO

SELECT
    TB_EMPREGADO.COD_DEPTO,
	TB_DEPARTAMENTO.DEPTO,
	AVG(SALARIO)		MEDIA_SALARIAL,
	SUM(SALARIO)		TOTAL_GASTO_SALARIO,
	MIN(SALARIO)		MENOR_SALARIO,
	MAX(SALARIO)		MAIOR_SALARIO,
	COUNT(*)			QTD_EMPREGADOS

FROM TB_EMPREGADO
	LEFT JOIN TB_DEPARTAMENTO
	ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
GROUP BY TB_EMPREGADO.COD_DEPTO, TB_DEPARTAMENTO.DEPTO

SELECT
    TB_DEPARTAMENTO.COD_DEPTO,
	TB_DEPARTAMENTO.DEPTO,
	AVG(SALARIO)		MEDIA_SALARIAL,
	SUM(SALARIO)		TOTAL_GASTO_SALARIO, 
	MIN(SALARIO)		MENOR_SALARIO,	  -- NAO RETORNA O NULO		
	MAX(SALARIO)		MAIOR_SALARIO,    -- NAO RETORNA O NULO 
	COUNT(CODFUN)		QTD_EMPREGADOS    -- COUNT NUNCA PODE SER NULO

FROM TB_EMPREGADO
	RIGHT JOIN TB_DEPARTAMENTO
	ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
GROUP BY TB_DEPARTAMENTO.COD_DEPTO, TB_DEPARTAMENTO.DEPTO

SELECT
    TB_DEPARTAMENTO.COD_DEPTO,
	TB_DEPARTAMENTO.DEPTO,
	AVG(SALARIO)		MEDIA_SALARIAL,
	SUM(SALARIO)		TOTAL_GASTO_SALARIO, 
	MIN(SALARIO)		MENOR_SALARIO,	  -- NAO RETORNA O NULO		
	MAX(SALARIO)		MAIOR_SALARIO,    -- NAO RETORNA O NULO 
	COUNT(CODFUN)		QTD_EMPREGADOS    -- COUNT NUNCA PODE SER NULO

FROM TB_EMPREGADO
	FULL JOIN TB_DEPARTAMENTO
	ON TB_EMPREGADO.COD_DEPTO = TB_DEPARTAMENTO.COD_DEPTO
GROUP BY TB_DEPARTAMENTO.COD_DEPTO, TB_DEPARTAMENTO.DEPTO

-- QUANTO EM DINHEIRO CADA VENDEDOR VENDEU POR CLIENTE

SELECT
	TB_PEDIDO.CODVEN,
	TB_VENDEDOR.NOME,
	TB_PEDIDO.CODCLI,
	TB_CLIENTE.NOME,
	SUM(VLR_TOTAL)         VALOR_TOTAL_POR_CLIENTE
FROM TB_PEDIDO
	INNER JOIN TB_VENDEDOR
	ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
	INNER JOIN TB_CLIENTE
	ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
GROUP BY TB_PEDIDO.CODVEN,
	TB_VENDEDOR.NOME,
	TB_PEDIDO.CODCLI,
	TB_CLIENTE.NOME
ORDER BY CODVEN, SUM(VLR_TOTAL)DESC

-- QUANTO EM DINHEIRO CADA VENDEDOR VENDEU POR CLIENTE UQE VENDEU MAIS DE 10MIL PARA UM CLIENTE 

SELECT
	TB_PEDIDO.CODVEN,
	TB_VENDEDOR.NOME,
	TB_PEDIDO.CODCLI,
	TB_CLIENTE.NOME,
	SUM(VLR_TOTAL)         VALOR_TOTAL_POR_CLIENTE
FROM TB_PEDIDO
	INNER JOIN TB_VENDEDOR
	ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
	INNER JOIN TB_CLIENTE
	ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
GROUP BY 
	TB_PEDIDO.CODVEN,
	TB_VENDEDOR.NOME,
	TB_PEDIDO.CODCLI,
	TB_CLIENTE.NOME
HAVING SUM(VLR_TOTAL) > 10000           --FILTRA DEPOIS DO GROUP BY!!!! FILTRA OS GRUPOS 
ORDER BY CODVEN, SUM(VLR_TOTAL)DESC     --FILTRO COM A FUNÇÃO DE AGREGAÇÃO USA NO HAVING 


-- ORDEM DE PRECEDÊNCIA (WHERE > GROUP BY > HAVING > ORDER BY)

-- ALIAS DE COLUNA SÓ FUNCIONA NO ORDER BY 

--DEPARTAMENTOS COM MAIS DE 2 FUNCIONÁRIOS ADMITIDOS APÓS O ANO 2000