USE DB_VENDAS 

--ORDENANDO O SELECT 
SELECT *            -- VEM SEMPRE ORDENADO PELA CHAVE
FROM TB_EMPREGADO 

--ORDENAÇÃO DEFINIDA PELO DEV 

-- EMPREGADOS EM ORDEM ALFABÉTICA PELO NOME DO FUNCIONÁRIO 
SELECT 
	*
FROM TB_EMPREGADO
ORDER BY NOME ASC -- ORDEM CRESCENTE

SELECT 
	*
FROM TB_EMPREGADO
ORDER BY NOME -- ORDEM CRESCENTE ASC É OPCIONAL 

--EXIBIR OS EMPREGADOS POR ORDEM DE SALÁRIO (DE MAIS PRA MENOS) 
SELECT 
	NOME,
	SALARIO
FROM TB_EMPREGADO 
ORDER BY SALARIO DESC -- ORDEM DECRESCENTE

SELECT 
	NOME
FROM TB_EMPREGADO 
ORDER BY SALARIO DESC -- ORDEM DECRESCENTE 

-- ORDENAR PELA POSIÇÃO DA COLUNA 
SELECT
	*
FROM TB_CLIENTE
ORDER BY 2 

SELECT 
	NOME,
	CIDADE
FROM TB_CLIENTE 
ORDER BY 2 


-- RESTRINGINDO QUANTIDADE DE REGISTRO NA SAÍDA 
-- 10 EMPREGADOS MAIS ANTIGOS 
SELECT TOP 10
	*
FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO

-- OS 8 EMPREGADOS MAIS NOVOS 
SELECT TOP 8
* FROM TB_EMPREGADO
ORDER BY DATA_NASCIMENTO DESC

-- EMPREGADO COM MAIOR SALARIO 
SELECT TOP 1 WITH TIES
	*
FROM TB_EMPREGADO 
ORDER BY SALARIO DESC

-- OS 4 EMPREGADOS COM MAIORES SALARIOS DA EMPRESA 
SELECT TOP 4 WITH TIES
	*
FROM TB_EMPREGADO 
ORDER BY SALARIO DESC

-- RETORNANDO UMA AMOSTRA PERCENTUAL DOS REGISTROS 
-- EXIBIR UMA AMOSTRA DE 1% DOS PEDIDOS VLR TOTAL 
SELECT TOP 1 PERCENT
	*
FROM TB_PEDIDO 
ORDER BY VLR_TOTAL

-- EXIBIR 5% DOS PEDIDOS ALEATÓRIAMENTE 
SELECT TOP 5 PERCENT
	*
FROM TB_PEDIDO
ORDER BY NEWID()

-- EXIBIR 1 EMPREGADO DE FORMA ALETORIA 
SELECT TOP 1 
*
FROM TB_EMPREGADO 
ORDER BY NEWID()
