use [2102341]

CREATE TABLE tb_aluno
(
	RA             int           not null,
	nm_aluno       Varchar(50)   not null,
	DT_Nascimento  DATE		
)

-- ALTERANDO UMA TABELA ADICIONANDO COLUNA
ALTER TABLE TB_ALUNO
	ADD DS_EMAIL VARCHAR(100)

-- ALTERANDO UMA TABELA REMOVER COLUNA
ALTER DROP TB_ALUNO
	DROP COLUMN DS_EMAIL

--ALTERANDO UMA COLUNA DA TABELA 
ALTER TABLE TB_ALUNO
	ALTER COLUMN DT_NASCIMENTO DATE NOT NULL
-- EXCLUÍNDO TABELA 
DROP TABLE TB_TESTE_GS

-- EXLUINDO A TABELA, CASO ELA EXISTA
DROP TABLE IF EXISTS TB_TESTE_GS

-- FORMA RAIZ DO COMANDO ACIMA 

IF EXISTS (SELECT * FROM SYS.TABLES
			WHERE NAME = 'TB_TESTE_GS')
	DROP TABLE TB_TESTE_GS 
-- sys.Tables são todas as tabelas do sistema
-- select consegue ver todas as tabelas do sistemas 

-- INCLUINDO A COLOUNA RENDA
ALTER TABLE TB_ALUNO
	ADD VL_RENDA DECIMAL(8,2) -- ADD VL_RENDA NUMERC(8,2)


-- VALORES POSSÍVEIS DE RENDA DO ALUNO
	999999,99  -- DECIMAL('QNT DE CASAS' ,
			   -- 'QNT DE CASAS DECIMAIS DO TOTAL) decimal pode ter ex(2,0)

