USE [2102341]

CREATE TABLE TB_TIPO_VOO 
(
	ID						TINYINT		IDENTITY,
	DS_TIPO_VOO				VARCHAR(17) NOT NULL,
	DS_CLASSIFICACAO_VOO	VARCHAR(11) NOT NULL,

	CONSTRAINT PK_TB_TIPO_VOO PRIMARY KEY (ID),
	CONSTRAINT UQ_DS_TIPO_VOO_TB_TIPO_VOO UNIQUE (DS_TIPO_VOO),
	CONSTRAINT CK_DS_TIPO_VOO_TB_TIPO_VOO 
	CHECK (DS_TIPO_VOO IN('REGULAR', 'EXTRA', 'RETORNO',
	'INCLUSÃO DE ETAPA', 'NÃO REMUNERADO', 'FRETAMENTO', 'CHARTER')),
	CONSTRAINT CK_DS_CLASSIFICACAO_VOO_TB_TIPO_VOO
	CHECK (DS_CLASSIFICACAO_VOO IN('REGULAR', 'NÃO REGULAR', 'IMPRODUTIVO'))
)