
version: "3.9"
services:
 web:
  build: .
  working_dir: /data
  command: python app2.py
  links:
    - db  #esse nome ---
  volumes:
    - .:/data
  ports:
    - "5000:5000"

 db: # tem que ser igual a esse ---
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: mudar123
  ports:
    - "3309:3309"