USE [2102341]

CREATE TABLE TABELA_DEP
(
	COD_DEPTO			TINYINT IDENTITY,
	DEPTO				VARCHAR(15) NOT NULL,

	CONSTRAINT PK_TABELA_DEP PRIMARY KEY (COD_DEPTO),
	CONSTRAINT UN_DEPTO UNIQUE (DEPTO)
)

CREATE TABLE TABELA_CAR
(
	COD_CARGO		TINYINT IDENTITY,
	CARGO			VARCHAR(20) NOT NULL,
	SALARIO_INIC	SMALLINT NOT NULL,

	CONSTRAINT PK_TABELA_CAR PRIMARY KEY (COD_CARGO)
)

CREATE TABLE EMPREGADOS
(
	CODFUN			SMALLINT IDENTITY,
	NOME			VARCHAR(30) NOT NULL,
	NUM_DEPEND		TINYINT,
	DATA_NASCIMENTO DATE NOT NULL,
	COD_DEPTO		TINYINT NOT NULL,
	COD_CARGO		TINYINT NOT NULL,
	DATA_ADMISSAO	DATE NOT NULL,
	SALARIO			SMALLINT NOT NULL,
	SINDICALIZADO	CHAR(1),
	OBS				VARCHAR(50),

	CONSTRAINT PK_EMPREGADOS PRIMARY KEY (CODFUN),
	
	CONSTRAINT FK_EMPREGADO_COD_CARGO FOREIGN KEY (COD_CARGO)
	REFERENCES TABELA_CAR(COD_CARGO),

	CONSTRAINT FK_EMPREGADO_COD_DEPTO FOREIGN KEY (COD_DEPTO)
	REFERENCES TABELA_DEP(COD_DEPTO),
)

CREATE TABLE DEPENDENTES
(
	CODFUN				SMALLINT,
	CODDEP				TINYINT,
	NOME				VARCHAR(30),
	DATA_NASCIMENTO		DATE,
	
	CONSTRAINT PK_DEPENDENTES PRIMARY KEY (CODFUN, CODDEP)
)


