USE DB_VENDAS

SELECT TOP 1
	*
FROM TB_PRODUTO
WHERE PRECO_CUSTO > 0 AND DESCRICAO LIKE 'S%' 
ORDER BY QTD_REAL ASC

SELECT 
	*
FROM TB_PEDIDO 
WHERE DATA_EMISSAO BETWEEN '2018-01-01'AND'2018-12-31' 
AND SITUACAO = 'C'
ORDER BY CODCLI DESC, VLR_TOTAL ASC

SELECT
	DESCRICAO, ID_PRODUTO, QTD_REAL, QTD_MINIMA, QTD_REAL - QTD_MINIMA AS 'dif. quantidade'
FROM TB_PRODUTO

SELECT TOP 7 
	*
FROM TB_CARGO
