-- RETORNE OS CLIENTES (NOME) QUE COMPRARAM  MAIS DE 10 VEZES EM 2016.

USE DB_VENDAS
SELECT 
	TB_PEDIDO.CODCLI,
	TB_CLIENTE.NOME,
	COUNT(*)     QTD_PEDIDOS
FROM TB_PEDIDO
	 JOIN TB_CLIENTE
	ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI
WHERE YEAR(DATA_EMISSAO) = 2016
GROUP BY TB_PEDIDO.CODCLI,
		 TB_CLIENTE.NOME
HAVING COUNT(*) > 10

-- RETORNE OS VENDEDORES QUE VENDERAM MAIS DE r$100 MIL EM 2017.

SELECT 
	TB_VENDEDOR.NOME        NOME_VENDEDOR,
	TB_VENDEDOR.CODVEN      COD_VENDEDOR,
	SUM(VLR_TOTAL)          VALOR_TOTAL
FROM TB_PEDIDO
	JOIN TB_VENDEDOR
	ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
WHERE YEAR(DATA_EMISSAO) BETWEEN  '20170101' AND '20171231'
GROUP BY TB_VENDEDOR.CODVEN,
		 TB_VENDEDOR.NOME
HAVING SUM(VLR_TOTAL) > 100000 

SELECT * FROM tb_produto

-- EXIBA AS VENDAS (NUM_PEDIDO E DATA EMISSÃO) QUE POSSUEM MAIS DE UM ITEM VENDIDO.

SELECT
	TB_PEDIDO.NUM_PEDIDO,
	TB_PEDIDO.DATA_EMISSAO,
	COUNT(*)
	--MAX(TB_ITENSPEDIDO.NUM_ITEM)
FROM TB_ITENSPEDIDO
	INNER JOIN TB_PEDIDO
	ON TB_PEDIDO.NUM_PEDIDO = TB_ITENSPEDIDO.NUM_PEDIDO
GROUP BY 
	TB_PEDIDO.NUM_PEDIDO,
	TB_PEDIDO.DATA_EMISSAO
HAVING COUNT(*) > 1

-- EXIBA OS FORNECEDORES E A QUANTIDADE DE PRODUTOS QUE ELE FORNECE.

SELECT 
	TB_FORNECEDOR.COD_FORNECEDOR    COD_FORNECEDOR,
	TB_FORNECEDOR.NOME				ID_PRODUTO,
	COUNT(*)					    QUANT_PRODUTOS
FROM TB_PROD_FORN
	JOIN TB_FORNECEDOR
	ON TB_FORNECEDOR.COD_FORNECEDOR = TB_PROD_FORN.COD_FORNECEDOR
GROUP BY 
	TB_FORNECEDOR.COD_FORNECEDOR,
	TB_FORNECEDOR.NOME

-- EXIBA OS PRODUTOS QUE POSSUEM MAIS DE UM FORNECEDOR CADSTRADO.

SELECT 
	TB_PRODUTO.DESCRICAO,
	TB_PRODUTO.ID_PRODUTO,
	COUNT(COD_FORNECEDOR)
FROM TB_PRODUTO
	INNER JOIN TB_PROD_FORN
	ON TB_PRODUTO.ID_PRODUTO = TB_PROD_FORN.ID_PRODUTO
GROUP BY 
	TB_PRODUTO.DESCRICAO,
	TB_PRODUTO.ID_PRODUTO
HAVING COUNT(COD_FORNECEDOR) > 1 

-- CRIE UM SELECT QUE RETORNE, POR CLIENTE, A DATA DA PRIMEIRA COMPRA, A DATA DA ÚLTIMA COMPRA, 
-- QUANTIDADE COMPRADA E O VALOR TOTAL GASTO PELO CLIENTE. RETORNE APENAS OS 10 CLIENTES QUE MAIS COMPRARAM EM QUANTIDADE.
SELECT TOP 10 WITH TIES
	TB_CLIENTE.CODCLI,
	TB_CLIENTE.NOME,
	MIN(DATA_EMISSAO)	DT_PRIMEIRA_COMPRA,
	MAX(DATA_EMISSAO)	DT_ULTIMA_COMPRA,
	COUNT(NUM_PEDIDO)	QTD_COMPRAS,
	SUM(VLR_TOTAL)		VL_GASTO_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_PEDIDO
	ON TB_PEDIDO.CODCLI = TB_CLIENTE.CODCLI
GROUP BY
	TB_CLIENTE.CODCLI,
	TB_CLIENTE.NOME
ORDER BY QTD_COMPRAS DESC

-- CRIE UM SELECT QUE RETORNE POR ANO E MÊS A QUANTIDADE DE VENDAS E A SOMA DO VALOR TOTAL VENDIDO.
SELECT 
	YEAR(DATA_EMISSAO)	AS ANO_VENDA,
	MONTH(DATA_EMISSAO) AS MES_VENDA,
	COUNT(NUM_PEDIDO)	AS QTD_VENDA,
	SUM(VLR_TOTAL)		AS VLR_FATURAMENTO
FROM TB_PEDIDO
GROUP BY 
	YEAR(DATA_EMISSAO),
	MONTH(DATA_EMISSAO)
ORDER BY 
	ANO_VENDA,
	MES_VENDA

-- CRIE UM SELECT QUE RETORNE 
-- NA PRIMEIRA COLUNA O NOME DO VENDEDOR, 
-- NA SEGUNDA COLUNA O TOTAL VENDIDO EM 2016, 
-- NA TERCEIRA COLUNA O TOTAL VENDIDO EM 2017, 
-- NA QUARTA COLUNA O TOTAL VENDIDO EM 2018,
-- NA QUINTA COLUNA O TOTAL VENDIDO EM 2019 
-- E NA SEXTA COLUNA O TOTAL VENDIDO INDEPENDENTE DO ANO.

SELECT
	TB_VENDEDOR.NOME AS VENDEDOR,
	SUM(CASE WHEN YEAR(DATA_EMISSAO) = 2016 THEN VLR_TOTAL END) VLR_TOTAL_2016,
	SUM(CASE WHEN YEAR(DATA_EMISSAO) = 2017 THEN VLR_TOTAL END) VLR_TOTAL_2017,
	SUM(CASE WHEN YEAR(DATA_EMISSAO) = 2018 THEN VLR_TOTAL END) VLR_TOTAL_2018,
	SUM(CASE WHEN YEAR(DATA_EMISSAO) = 2019 THEN VLR_TOTAL END) VLR_TOTAL_2019
FROM TB_PEDIDO
	INNER JOIN TB_VENDEDOR
	ON TB_PEDIDO.CODVEN = TB_VENDEDOR.CODVEN
GROUP BY TB_VENDEDOR.NOME


SELECT
	VENDAS_2016.NOME,
	VENDAS_2016.VLR_TOTAL  AS VLR_TOTAL_2016,
	VENDAS_2017.VLR_TOTAL  AS VLR_TOTAL_2017,
	VENDAS_2018.VLR_TOTAL  AS VLR_TOTAL_2018,
	VENDAS_2019.VLR_TOTAL  AS VLR_TOTAL_2019,
	VENDAS.VLR_TOTAL  AS VLR_TOTAL
FROM 
		(-- VALOR TOTAL VENDIDO POR VENDEDOR EM 2016
			SELECT NOME, SUM(VLR_TOTAL) AS VLR_TOTAL
			FROM TB_VENDEDOR INNER JOIN TB_PEDIDO ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
			WHERE YEAR(DATA_EMISSAO) = 2016
			GROUP BY NOME 
		) AS VENDAS_2016
		INNER JOIN 
		(-- VALOR TOTAL VENDIDO POR VENDEDOR EM 2017
			SELECT NOME, SUM(VLR_TOTAL) AS VLR_TOTAL
			FROM TB_VENDEDOR INNER JOIN TB_PEDIDO ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
			WHERE YEAR(DATA_EMISSAO) = 2017
			GROUP BY NOME 
		) AS VENDAS_2017
		ON VENDAS_2016.NOME = VENDAS_2017.NOME
		INNER JOIN 
		(-- VALOR TOTAL VENDIDO POR VENDEDOR EM 2018
			SELECT NOME, SUM(VLR_TOTAL) AS VLR_TOTAL
			FROM TB_VENDEDOR INNER JOIN TB_PEDIDO ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
			WHERE YEAR(DATA_EMISSAO) = 2018
			GROUP BY NOME 
		) AS VENDAS_2018
		ON VENDAS_2016.NOME = VENDAS_2018.NOME
		INNER JOIN 
		(-- VALOR TOTAL VENDIDO POR VENDEDOR EM 2019
			SELECT NOME, SUM(VLR_TOTAL) AS VLR_TOTAL
			FROM TB_VENDEDOR INNER JOIN TB_PEDIDO ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
			WHERE YEAR(DATA_EMISSAO) = 2019
			GROUP BY NOME 
		) AS VENDAS_2019
		ON VENDAS_2016.NOME = VENDAS_2019.NOME
		INNER JOIN
		(-- VALOR TOTAL VENDIDO POR VENDEDOR
			SELECT NOME, SUM(VLR_TOTAL) AS VLR_TOTAL
			FROM TB_VENDEDOR INNER JOIN TB_PEDIDO ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN
			GROUP BY NOME 
		) AS VENDAS
		ON VENDAS_2016.NOME = VENDAS.NOME