USE [DB_VENDAS]

-- EXERCICIO 2

SELECT 
	COD_PRODUTO, DESCRICAO, PRECO_CUSTO, PRECO_VENDA, PRECO_CUSTO - PRECO_VENDA  AS LUCRO
FROM TB_PRODUTO

-- EXERCICIO 3 

SELECT
	COD_PRODUTO, DESCRICAO, QTD_REAL * PRECO_CUSTO AS TOTAL_INVESTIDO 
FROM TB_PRODUTO

-- EXERCICIO 4

SELECT	
	NUM_PEDIDO, NUM_ITEM, COD_PRODUTO, PR_UNITARIO, QUANTIDADE, DESCONTO, 
	PR_UNITARIO * QUANTIDADE - (DESCONTO/100)
FROM TB_ITENSPEDIDO

-- EXERCICIO 5

SELECT
	COD_PRODUTO, DESCRICAO, PRECO_CUSTO, PRECO_VENDA, 
	QTD_REAL * (PRECO_CUSTO - PRECO_VENDA)
FROM TB_PRODUTO

-- EXERCICIO 6 

SELECT
	COD_PRODUTO, DESCRICAO, PRECO_CUSTO, PRECO_VENDA,
	(PRECO_VENDA - PRECO_CUSTO) AS LUCRO_U,
	((100*(PRECO_VENDA- PRECO_CUSTO) / PRECO_CUSTO)) AS LUCRO_U_PERCENTUAL
FROM TB_PRODUTO 
WHERE PRECO_CUSTO > 0 

-- EXERCICIO 7 

SELECT
	(QTD_REAL - QTD_MINIMA) AS CAUCULADO
FROM TB_PRODUTO
WHERE QTD_REAL < QTD_MINIMA

--EXERCICIO 8 
SELECT 
	*
FROM TB_PRODUTO
WHERE QTD_REAL > 5000

--EXERCICIO 9
SELECT
	*
FROM TB_PRODUTO
WHERE PRECO_VENDA < 0.50

-- EXERCICIO 10
SELECT
	*
FROM TB_PEDIDO 
WHERE VLR_TOTAL > 15000

--EXERCICIO 11 

SELECT
*
FROM TB_PRODUTO
WHERE QTD_REAL BETWEEN 500 AND 1000

--EXERCICIO 12

SELECT
*
FROM TB_PEDIDO 
WHERE VLR_TOTAL BETWEEN 15000 AND 25000

-- EXERCICIO 13

SELECT 
	* 
FROM TB_PRODUTO
WHERE QTD_REAL > 5000 AND COD_TIPO = 6

-- EXERCICIO 14

SELECT
	*
FROM TB_PRODUTO
WHERE QTD_REAL > 5000 OR COD_TIPO = 6

--EXERCICIO 15

SELECT 
	*
FROM TB_PEDIDO
WHERE VLR_TOTAL < 100 OR VLR_TOTAL > 100000

--EXERCICIO 16 

SELECT * 
FROM TB_PRODUTO
WHERE QTD_REAL < 500 OR QTD_REAL > 1000

-- EXERCICIO 17
SELECT * 
FROM TB_CLIENTE
WHERE ESTADO = 'SP'

-- EXERCICIO 18
SELECT * 
FROM TB_CLIENTE
WHERE ESTADO = 'MG' OR ESTADO = 'RJ'

-- EXERCICIO 19

SELECT * 
FROM TB_CLIENTE
WHERE ESTADO = 'MG' OR ESTADO = 'SP' OR ESTADO = 'RJ'

-- EXERCICIO 20
SELECT *
FROM TB_VENDEDOR 
WHERE NOME LIKE 'LEIA'

--EXERCICIO 21
SELECT *
FROM TB_CLIENTE
WHERE NOME LIKE 'BRINDES%'

--EXERCICIO 22
SELECT *
FROM TB_CLIENTE
WHERE NOME LIKE '%BRINDES'

-- EXERCICIO 23
SELECT *
FROM TB_CLIENTE
WHERE NOME LIKE '%BRINDES%'

-- EXERCICIO 24
SELECT * 
FROM TB_PRODUTO
WHERE DESCRICAO LIKE 'CANETA%'

-- EXERCICIO 25
SELECT * 
FROM TB_PRODUTO
WHERE DESCRICAO LIKE '%SPECIAL%'

-- EXERCICIO 26
SELECT * 
FROM TB_PRODUTO
WHERE DESCRICAO LIKE '%GOLD'

-- EXERCICIO 27
SELECT * 
FROM TB_CLIENTE
WHERE NOME LIKE '_A%'

-- EXERCICIO 28
SELECT*
FROM TB_PRODUTO
WHERE COD_PRODUTO LIKE '_0%'

-- EXERCICIO 29
SELECT*
FROM TB_PRODUTO
WHERE COD_PRODUTO LIKE '__0%'

--EXERCICIO 30
SELECT*
FROM TB_PEDIDO
WHERE DATA_EMISSAO < '2016 - 01 - 01'

-- EXERCICIO 31

SELECT *
FROM TB_PEDIDO 
WHERE DATA_EMISSAO BETWEEN '2016 - 01 - 01' AND '2016 - 06 - 30' 

-- EXERCICIO 32 

SELECT *
FROM TB_PEDIDO 
WHERE DATA_EMISSAO BETWEEN '2016 - 01 - 01' AND '2016 - 01 - 31' OR 
	  DATA_EMISSAO BETWEEN '2016 - 06 - 01' AND '2016 - 06 - 30'
	
-- EXERCICIO 33 

SELECT * 
FROM TB_VENDEDOR 
WHERE CODVEN = 1 AND  BETWEEN '2016 - 01 - 01' _AND '2016-01-31'










_