USE DB_HELPDESK

-- EXERCICIO 1 
SELECT DISTINCT
	TB_STATUS.NM_STATUS NOME_STATUS
FROM TB_CHAMADO
	INNER JOIN TB_STATUS
	ON TB_CHAMADO.ID_STATUS = TB_STATUS.ID_STATUS
WHERE DT_FECHAMENTO IS NULL

-------------------------------------

-- EXERCICIO 2 
SELECT TB_STATUS.ID_STATUS  ID,
	   NM_STATUS  NOME_STATUS
FROM TB_STATUS
	LEFT OUTER JOIN TB_CHAMADO
	ON TB_STATUS.ID_STATUS = TB_CHAMADO.ID_STATUS
WHERE TB_CHAMADO.ID_STATUS IS NULL


--------------------------------------

--EXERCICIO 3 
SELECT 
	ID_CHAMADO,
	FORMAT(DT_ABERTURA, 'DD/MM') DATA_ABERTURA,
	FORMAT(DT_FECHAMENTO, 'DD/MM') DATA_FECHAMENTO,
	LEFT(TB_USUARIO.NM_USUARIO, CHARINDEX(' ',TRIM(TB_USUARIO.NM_USUARIO))) PRIMEIRO_NOME,
	DATEDIFF(MINUTE, DT_ABERTURA, DT_FECHAMENTO) DIFERENCA_MINUTOS
FROM TB_CHAMADO
	JOIN TB_USUARIO
	ON TB_CHAMADO.ID_USUARIO_SOLICITANTE = TB_USUARIO.ID_USUARIO
WHERE ID_STATUS = 4
