USE [2102341]

CREATE TABLE TB_AERODROMO
(	
	ID					SMALLINT		IDENTITY,
	SG_AERODROMO		CHAR(4) NOT NULL,
	NM_AERODROMO		VARCHAR(100) NOT NULL,
	NM_CIDADE			VARCHAR(50),
	SG_UF				CHAR(2),
	NM_PAIS				VARCHAR(50) NOT NULL,
	NM_CONTINENTE		VARCHAR(16) NOT NULL,

	CONSTRAINT PK_TB_AERODROMO PRIMARY KEY (ID),
	CONSTRAINT UQ_SG_AERODROMO_TB_AERODROMO UNIQUE (SG_AERODROMO),
	CONSTRAINT UQ_NM_AERODROMO_TB_AERODROMO UNIQUE (NM_AERODROMO),
	CONSTRAINT CK_CONTINENTE_TB_AERODROMO 
	CHECK(NM_CONTINENTE IN('AMERICA DO SUL', 'OCEANIA', 'AMERICA DO NORTE','AMERICA CENTRAL', 'AFRICA', 'EUROPA', 'ASIA'))

)
CREATE TABLE TB_EMPRESA 
(
	ID				TINYINT		IDENTITY, 
	SG_EMPRESA		CHAR(3) NOT NULL,
	NM_EMPREA		VARCHAR(100) NOT NULL,
	DS_TIPO_EMPRESA VARCHAR(13) NOT NULL,

	CONSTRAINT PK_TB_EMPRESA PRIMARY KEY (ID),
	CONSTRAINT CK_DS_TIPO_EMPREA_TB_EMPRESA CHECK (DS_TIPO_EMPRESA IN ('BRASILEIRA','ESTRANGEIRA', 'NÃO INFORMADO'))
)