USE [2102341]

CREATE TABLE TB_EMPRESA 
(
	ID				TINYINT		IDENTITY, 
	SG_EMPRESA		CHAR(3) NOT NULL,
	NM_EMPREA		VARCHAR(100) NOT NULL,
	DS_TIPO_EMPRESA VARCHAR(13) NOT NULL,

	CONSTRAINT PK_TB_EMPRESA PRIMARY KEY (ID),
	CONSTRAINT CK_DS_TIPO_EMPREA_TB_EMPRESA CHECK (DS_TIPO_EMPRESA IN ('BRASILEIRA','ESTRANGEIRA', 'NÃO INFORMADO'))
)