USE [2102341]

CREATE TABLE TB_JUSTIFICATIVA
(
	ID					TINYINT		IDENTITY,
	SG_JUSTIFICATIVA	CHAR(2) NOT NULL,
	DS_JUSTIFICATIVA	VARCHAR(100) NOT NULL,

	CONSTRAINT PK_TB_JUSTIFICATIVA PRIMARY KEY (ID),
	CONSTRAINT UQ_SG_JUSTIFICATIVA_TB_JUSTIFICATIVA UNIQUE (SG_JUSTIFICATIVA)
)