USE [2102341]

CREATE TABLE TB_TIPO_LINHA
(
	ID						TINYINT		IDENTITY,
	CD_TIPO_LINHA			CHAR(1) NOT NULL,
	DS_SERVICO_TIPO_LINHA	VARCHAR(9) NOT NULL,
	DS_NATUREZA_TIPO_LINHA  VARCHAR(13) NOT NULL,

	CONSTRAINT PK_TB_TIPO_LINHA PRIMARY KEY (ID),
	CONSTRAINT UQ_CD_TIPO_LINHA_TB_TIPO_LINHA UNIQUE (CD_TIPO_LINHA),
	CONSTRAINT CK_CD_TIPO_LINHA CHECK (CD_TIPO_LINHA IN ('N', 'C', 'I', 'G')),
	CONSTRAINT CK_DS_SERVICO_TIPO_LINHA CHECK (DS_SERVICO_TIPO_LINHA IN ('MISTA', 'CARGUEIRA')),
	CONSTRAINT CK_DS_NATUREZA_TIPO_LINHA_TB_TIPO_LINHA 
	CHECK (DS_NATUREZA_TIPO_LINHA IN ('INTERNACIONAL', 'DOMÉSTICA'))

)